### ISSUE TITLE
Missing "input" GraphQL keyword for TypeConsumer?

### ISSUE THREAD

**Issue by ghost** [johanatan/graphql-type-lang-compiler#1]
It seems like "object", "type", and "union" types are accounted for, but I don't see a corresponding line for some sort "input" keyword around lines 82-84.

https://github.com/johanatan/graphql-type-lang-compiler/blob/master/src/graphql-tlc/schema.cljs

**Comment by johanatan** [comment]
The `TypeConsumer` consumes the parsed representations of types defined in type language (input schema). The only types supported are: enum, union & type (object).

I'm not sure what an 'input' type would be. Can you explain that?

**Comment by johanatan** [comment]
Out-of-band discussion revealed:
http://graphql.org/learn/schema/#input-types

This sounds like a nice addition. I've marked the 'issue' as 'enhancement'.
